baseURL = 'https://jamesmr13.github.io/'
languageCode = 'en-us'
theme = 'nightfall'
[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"
  [[menu.header]]
    name = "publications"
    weight = 2
    url = "publications"

[params]
author = "James Robertson"
user = "hello"
hostname = "jamesmr13.github.io"

readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "github"
url = "https://github.com/jamesmr13"

[[params.social]]
key = 1
name = "twitter"
url = "https://www.example.com"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.example.com"

[[params.social]]
key = 3
name = "email"
url = "mailto:email@example.com"
